### PR TITLE
Stabilize fetch_update, fetch_min and fetch_max

### PR DESCRIPTION
**Pull request by mexus**
fetch_update, fetch_min and fetch_max are now on stable! since 1.45.0 :)

### CODE REVIEW

**Comment by mexus** [comment]
I'm not quite sure though whether new version should be 0.2 or 0.1.1

**Comment by mexus** [comment]
@flier if I understand correctly, CI fails on old compilers because `cfg_if` doesn't support them anymore. I guess I could try to remove `cfg_if` completely, but another option would be to simply drop support for the old versions :)

**Comment by flier** [comment]
Bump version to 0.2, thanks @mexus 👍

**Comment by mexus** [comment]
Thanks! :)

**Pull request merged**
